### Importing Libraries

In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV

print("Libraries Imported !")

Libraries Imported !


### Making Dataset With Features

In [24]:
np.random.seed(42)

x = np.random.rand(100, 20)
y = 3*x[:,0] + 2*x[:, 1] + 5*x[:,2] + np.random.randn(100)

In [25]:
x[:10]

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
        0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
        0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
        0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
        0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
        0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
        0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446,
        0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
        0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
        0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694,
        0.77224477, 0.19871568, 0.00552212, 0

In [26]:
y[:10]

array([5.80703609, 2.74838929, 1.30193224, 6.21978299, 6.40398128,
       2.13570933, 7.29720901, 5.6060254 , 5.51424232, 5.12640251])

### Feature Scaling

In [27]:
sc = StandardScaler()
x = sc.fit_transform(x)
x[:10]

array([[-0.39489759,  1.51882043,  0.97105105,  0.34519575, -1.18962206,
        -1.25571366, -1.43699549,  1.24744732,  0.34147137,  0.78245737,
        -1.49304258,  1.41870739,  1.07158904, -0.99652812, -0.97942124,
        -1.15603028, -0.56375441,  0.15961244, -0.24568023, -0.66701144],
       [ 0.38853055, -1.1818259 , -0.63791108, -0.52612113, -0.20811948,
         0.9387329 , -0.94090612, -0.01570113,  0.31265303, -1.56693329,
         0.46415798, -1.42365098, -1.50965007,  1.59329123,  1.58776784,
         0.9259542 , -0.56250804, -1.39882999,  0.5759379 , -0.14570125],
       [-1.22846872,  0.00228395, -1.58077914,  1.5104514 , -0.85347785,
         0.51094384, -0.54836113,  0.00523609,  0.16126745, -1.07546674,
         1.67136805,  0.72614296,  1.43168956,  1.40321368,  0.38334171,
         1.30396992, -1.28753306, -1.04009136, -1.50509127, -0.54763931],
       [-0.34822729, -0.74286484,  1.32493757, -0.56216153, -0.78100784,
         0.09301639, -1.1467469 ,  1.01782071, -

### Alpha List

In [28]:
alpha = np.logspace(-2,2,50)
alpha

array([1.00000000e-02, 1.20679264e-02, 1.45634848e-02, 1.75751062e-02,
       2.12095089e-02, 2.55954792e-02, 3.08884360e-02, 3.72759372e-02,
       4.49843267e-02, 5.42867544e-02, 6.55128557e-02, 7.90604321e-02,
       9.54095476e-02, 1.15139540e-01, 1.38949549e-01, 1.67683294e-01,
       2.02358965e-01, 2.44205309e-01, 2.94705170e-01, 3.55648031e-01,
       4.29193426e-01, 5.17947468e-01, 6.25055193e-01, 7.54312006e-01,
       9.10298178e-01, 1.09854114e+00, 1.32571137e+00, 1.59985872e+00,
       1.93069773e+00, 2.32995181e+00, 2.81176870e+00, 3.39322177e+00,
       4.09491506e+00, 4.94171336e+00, 5.96362332e+00, 7.19685673e+00,
       8.68511374e+00, 1.04811313e+01, 1.26485522e+01, 1.52641797e+01,
       1.84206997e+01, 2.22299648e+01, 2.68269580e+01, 3.23745754e+01,
       3.90693994e+01, 4.71486636e+01, 5.68986603e+01, 6.86648845e+01,
       8.28642773e+01, 1.00000000e+02])

### Training Model With Lasso

In [29]:
lasso_cv = LassoCV(alphas=alpha, cv=10, random_state=42)
lasso_cv.fit(x, y)

LassoCV(alphas=array([1.00000000e-02, 1.20679264e-02, 1.45634848e-02, 1.75751062e-02,
       2.12095089e-02, 2.55954792e-02, 3.08884360e-02, 3.72759372e-02,
       4.49843267e-02, 5.42867544e-02, 6.55128557e-02, 7.90604321e-02,
       9.54095476e-02, 1.15139540e-01, 1.38949549e-01, 1.67683294e-01,
       2.02358965e-01, 2.44205309e-01, 2.94705170e-01, 3.55648031e-01,
       4.29193426e-01, 5.17947468e-0...
       1.93069773e+00, 2.32995181e+00, 2.81176870e+00, 3.39322177e+00,
       4.09491506e+00, 4.94171336e+00, 5.96362332e+00, 7.19685673e+00,
       8.68511374e+00, 1.04811313e+01, 1.26485522e+01, 1.52641797e+01,
       1.84206997e+01, 2.22299648e+01, 2.68269580e+01, 3.23745754e+01,
       3.90693994e+01, 4.71486636e+01, 5.68986603e+01, 6.86648845e+01,
       8.28642773e+01, 1.00000000e+02]),
        cv=10, random_state=42)

### Best Alpha

In [30]:
    print("Best Alpha : ", lasso_cv.alpha_)

Best Alpha :  0.054286754393238594


### Checking Coefficients

In [31]:
coeff = lasso_cv.coef_
coeff

array([ 0.70826183,  0.50485812,  1.34890323, -0.10541437,  0.        ,
       -0.1044108 ,  0.18991636, -0.        ,  0.        , -0.05341364,
        0.10730371, -0.1437068 ,  0.07250767, -0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.03901169, -0.03103625])

### Selecting Necessary Features

In [32]:
feature_importance = pd.DataFrame({
    "Feature": [f"Feature_{i}" for i in range(len(coeff))],
    "Coefficient": coeff
})

selected_features = feature_importance[feature_importance["Coefficient"] != 0]
selected_features

Feature  Coefficient
0    Feature_0     0.708262
1    Feature_1     0.504858
2    Feature_2     1.348903
3    Feature_3    -0.105414
5    Feature_5    -0.104411
6    Feature_6     0.189916
9    Feature_9    -0.053414
10  Feature_10     0.107304
11  Feature_11    -0.143707
12  Feature_12     0.072508
18  Feature_18    -0.039012
19  Feature_19    -0.031036